Browser=chrome
env=dev
appPackage=com.nthdegree.onsight.

#Admin
staging_username=chandani.kumari@dreamorbit.com
portal_admin_url=https://onsight-stage.nthdegree.com/
SystemAdminUsername=TestOnsightWA-Admin
orgCoreUsername_staging=chandani.kumari@dreamorbit.com
orgCorePassword=0OkMnJi(8UhB